---
- 
  gcp_container_cluster: 
    auth_kind: "{{ auth_kind }}"
    description: "Sanka Test Cluster"
    initial_node_count: "{{ initial_node_count }}"
    location: "{{ zone }}"
    locations: "{{ node_location }}"
    #    master_auth: 
    #      password: "{{ password }}"
    #      username: "{{ username }}"
    name: "{{ gkename }}"
    node_config: 
      disk_size_gb: "{{ disk_size_gb }}"
      machine_type: "{{ machine_type }}"
    ip_allocation_policy:
      create_subnetwork: "yes"
      subnetwork_name: "testgkecluster"
      use_ip_aliases: "yes"
    private_cluster_config: 
      enable_private_endpoint: "yes"
      enable_private_nodes: "yes"
      master_ipv4_cidr_block: 172.16.0.0/28
    project: "{{ project }}"
    scopes: 
      - "https://www.googleapis.com/auth/cloud-platform"
    service_account_file: "{{ service_account_file }}"
    state: absent
  name: "Delete GKE cluster"
  register: cluster
- 
  gcp_container_node_pool: 
    auth_kind: "{{ auth_kind }}"
    cluster: "{{ cluster }}"
    initial_node_count: "{{ np_initial_node_count }}"
    name: "{{ npname }}"
    project: "{{ project }}"
    scopes: 
      - "https://www.googleapis.com/auth/cloud-platform"
    service_account_file: "{{ service_account_file }}"
    state: absent
    location: "{{ zone }}"
    config:
      disk_size_gb: "{{ disk_size_gb }}"
      disk_type: "{{ disk_type }}"
      #      labels: "{{ labels_list }}"
    management:
      auto_repair: "no"
      auto_upgrade: "yes"
    autoscaling:
      enabled: "yes"
      max_node_count: "{{ max_node_np }}"
      min_node_count: "{{ min_node_np }}"
  name: "Delete the node pool"

#- name: Delete GKE network
#  shell: gcloud compute networks delete {{ k8_network_name }}

